import Navbar from "@/components/Navbar/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
// import { Providers } from "./libs/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mawaah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="h-screen font-['Roboto'] font-normal">
        <Navbar />
        <div className="mt-20">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
