import Navbar from "@/components/Navbar/navbar";
import "./globals.css";
// import { Inter, Roboto } from "next/font/google";
import { JetBrains_Mono as FontMono, Inter as FontSans } from "next/font/google"
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider"

// const inter = Inter({ subsets: ["latin"], display: 'swap' });
// const roboto = Roboto({ weight: "400", subsets: ["latin"] })

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata = {
  title: "Mawaah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={fontSans.className}>
      <body className="h-screen  bg-background ">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Navbar />
          <div className="mt-20">{children}</div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
